demogs = ['central_heating_perc_Does not apply',
 'central_heating_perc_No central heating',
 'central_heating_perc_Mains gas only',
 'central_heating_perc_Tank or bottled gas only',
 'central_heating_perc_Electric only',
 'central_heating_perc_Oil only',
 'central_heating_perc_Wood only',
 'central_heating_perc_Solid fuel only',
 'central_heating_perc_Renewable energy only',
 'central_heating_perc_District or communal heat networks only',
 'central_heating_perc_Other central heating only',
 'central_heating_perc_Two or more types of central heating (not including renewable energy)',
 'central_heating_perc_Two or more types of central heating (including renewable energy)',
 'socio_class_perc_Does not apply',
 'socio_class_perc_L1, L2 and L3: Higher managerial, administrative and professional occupations',
 'socio_class_perc_L4, L5 and L6: Lower managerial, administrative and professional occupations',
 'socio_class_perc_L7: Intermediate occupations',
 'socio_class_perc_L8 and L9: Small employers and own account workers',
 'socio_class_perc_L10 and L11: Lower supervisory and technical occupations',
 'socio_class_perc_L12: Semi-routine occupations',
 'socio_class_perc_L13: Routine occupations',
 'socio_class_perc_L14.1 and L14.2: Never worked and long-term unemployed',
 'socio_class_perc_L15: Full-time students',
 'household_comp_perc_Does not apply',
 'household_comp_perc_One-person household',
 'household_comp_perc_Single family household: All aged 66 years and over',
 'household_comp_perc_Single family household: Couple family household',
 'household_comp_perc_Single family household: Lone parent household',
 'household_comp_perc_Other household types',
 'sex_perc_Female',
 'sex_perc_Male',
 'bedroom_number_perc_Does not apply',
 'bedroom_number_perc_1 bedroom',
 'bedroom_number_perc_2 bedrooms',
 'bedroom_number_perc_3 bedrooms',
 'bedroom_number_perc_4 or more bedrooms',
 'deprivation_perc_Does not apply',
 'deprivation_perc_Household is not deprived in any dimension',
 'deprivation_perc_Household is deprived in one dimension',
 'deprivation_perc_Household is deprived in two dimensions',
 'deprivation_perc_Household is deprived in three dimensions',
 'deprivation_perc_Household is deprived in four dimensions',
 'tenure_perc_Does not apply',
 'tenure_perc_Owned: Owns outright',
 'tenure_perc_Owned: Owns with a mortgage or loan',
 'tenure_perc_Shared ownership: Shared ownership',
 'tenure_perc_Social rented: Rents from council or Local Authority',
 'tenure_perc_Social rented: Other social rented',
 'tenure_perc_Private rented: Private landlord or letting agency',
 'tenure_perc_Private rented: Other private rented',
 'tenure_perc_Lives rent free',
 'occupancy_rating_perc_Does not apply',
 'occupancy_rating_perc_Occupancy rating of bedrooms: +2 or more',
 'occupancy_rating_perc_Occupancy rating of bedrooms: +1',
 'occupancy_rating_perc_Occupancy rating of bedrooms: 0',
 'occupancy_rating_perc_Occupancy rating of bedrooms: -1',
 'occupancy_rating_perc_Occupancy rating of bedrooms: -2 or less',
 'household_siz_perc_perc_0 people in household',
 'household_siz_perc_perc_1 person in household',
 'household_siz_perc_perc_2 people in household',
 'household_siz_perc_perc_3 people in household',
 'household_siz_perc_perc_4 people in household',
 'household_siz_perc_perc_5 people in household',
 'household_siz_perc_perc_6 people in household',
 'household_siz_perc_perc_7 people in household',
 'household_siz_perc_perc_8 or more people in household',
 'ethnic_group_perc_Does not apply',
 'ethnic_group_perc_Asian, Asian British or Asian Welsh: Bangladeshi',
 'ethnic_group_perc_Asian, Asian British or Asian Welsh: Chinese',
 'ethnic_group_perc_Asian, Asian British or Asian Welsh: Indian',
 'ethnic_group_perc_Asian, Asian British or Asian Welsh: Pakistani',
 'ethnic_group_perc_Asian, Asian British or Asian Welsh: Other Asian',
 'ethnic_group_perc_Black, Black British, Black Welsh, Caribbean or African: African',
 'ethnic_group_perc_Black, Black British, Black Welsh, Caribbean or African: Caribbean',
 'ethnic_group_perc_Black, Black British, Black Welsh, Caribbean or African: Other Black',
 'ethnic_group_perc_Mixed or Multiple ethnic groups: White and Asian',
 'ethnic_group_perc_Mixed or Multiple ethnic groups: White and Black African',
 'ethnic_group_perc_Mixed or Multiple ethnic groups: White and Black Caribbean',
 'ethnic_group_perc_Mixed or Multiple ethnic groups: Other Mixed or Multiple ethnic groups',
 'ethnic_group_perc_White: English, Welsh, Scottish, Northern Irish or British',
 'ethnic_group_perc_White: Irish',
 'ethnic_group_perc_White: Gypsy or Irish Traveller',
 'ethnic_group_perc_White: Roma',
 'ethnic_group_perc_White: Other White',
 'ethnic_group_perc_Other ethnic group: Arab',
 'ethnic_group_perc_Other ethnic group: Any other ethnic group',
 'occupation_perc_Does not apply',
 'occupation_perc_1. Managers, directors and senior officials',
 'occupation_perc_2. Professional occupations',
 'occupation_perc_3. Associate professional and technical occupations',
 'occupation_perc_4. Administrative and secretarial occupations',
 'occupation_perc_5. Skilled trades occupations',
 'occupation_perc_6. Caring, leisure and other service occupations',
 'occupation_perc_7. Sales and customer service occupations',
 'occupation_perc_8. Process, plant and machine operatives',
 'occupation_perc_9. Elementary occupations',
 'highest_qual_perc_Does not apply',
 'highest_qual_perc_No qualifications',
 'highest_qual_perc_Level 1 and entry level qualifications: 1 to 4 GCSEs grade A* to C, Any GCSEs at other grades, O levels or CSEs (any grades), 1 AS level, NVQ level 1, Foundation GNVQ, Basic or Essential Skills',
 'highest_qual_perc_Level 2 qualifications: 5 or more GCSEs (A* to C or 9 to 4), O levels (passes), CSEs (grade 1), School Certification, 1 A level, 2 to 3 AS levels, VCEs, Intermediate or Higher Diploma, Welsh Baccalaureate Intermediate Diploma, NVQ level 2, Intermediate GNVQ, City and Guilds Craft, BTEC First or General Diploma, RSA Diploma',
 'highest_qual_perc_Apprenticeship',
 'highest_qual_perc_Level 3 qualifications: 2 or more A levels or VCEs, 4 or more AS levels, Higher School Certificate, Progression or Advanced Diploma, Welsh Baccalaureate Advance Diploma, NVQ level 3; Advanced GNVQ, City and Guilds Advanced Craft, ONC, OND, BTEC National, RSA Advanced Diploma',
 'highest_qual_perc_Level 4 qualifications or above: degree (BA, BSc), higher degree (MA, PhD, PGCE), NVQ level 4 to 5, HNC, HND, RSA Higher Diploma, BTEC Higher level, professional qualifications (for example, teaching, nursing, accountancy)',
 'highest_qual_perc_Other: vocational or work-related qualifications, other qualifications achieved in England or Wales, qualifications achieved outside England or Wales (equivalent not stated or unknown)',
 'economic_activity_perc_Does not apply',
 'economic_activity_perc_Economically active (excluding full-time students): In employment: Employee: Part-time',
 'economic_activity_perc_Economically active (excluding full-time students): In employment: Employee: Full-time',
 'economic_activity_perc_Economically active (excluding full-time students): In employment: Self-employed with employees: Part-time',
 'economic_activity_perc_Economically active (excluding full-time students): In employment: Self-employed with employees: Full-time',
 'economic_activity_perc_Economically active (excluding full-time students): In employment: Self-employed without employees: Part-time',
 'economic_activity_perc_Economically active (excluding full-time students): In employment: Self-employed without employees: Full-time',
 'economic_activity_perc_Economically active (excluding full-time students): Unemployed: Seeking work or waiting to start a job already obtained: Available to start working within 2 weeks',
 'economic_activity_perc_Economically active and a full-time student: In employment: Employee: Part-time',
 'economic_activity_perc_Economically active and a full-time student: In employment: Employee: Full-time',
 'economic_activity_perc_Economically active and a full-time student: In employment: Self-employed with employees: Part-time',
 'economic_activity_perc_Economically active and a full-time student: In employment: Self-employed with employees: Full-time',
 'economic_activity_perc_Economically active and a full-time student: In employment: Self-employed without employees: Part-time',
 'economic_activity_perc_Economically active and a full-time student: In employment: Self-employed without employees: Full-time',
 'economic_activity_perc_Economically active and a full-time student: Unemployed: Seeking work or waiting to start a job already obtained: Available to start working within 2 weeks',
 'economic_activity_perc_Economically inactive: Retired',
 'economic_activity_perc_Economically inactive: Student',
 'economic_activity_perc_Economically inactive: Looking after home or family',
 'economic_activity_perc_Economically inactive: Long-term sick or disabled',
 'economic_activity_perc_Economically inactive: Other',]

rur = [ 'RUC21CD',
 'RUC21NM',
 'Urban_rural_flag']

age = [ 'Pre 1919',
 '1919-1944',
 '1945-1959',
 '1960-1979',
 '1980-1989',
 '1990-1999',
 'Post 1999',
 'all_none_age',
 '1919-1944_pct',
 '1945-1959_pct',
 '1960-1979_pct',
 '1980-1989_pct',
 '1990-1999_pct',
 'all_none_age_pct',
 'Post 1999_pct',
 'Pre 1919_pct', ] 

typ = [ 'Medium height flats 5-6 storeys',
 'Small low terraces',
 '3-4 storey and smaller flats',
 'Tall terraces 3-4 storeys',
 'Large semi detached',
 'Standard size detached',
 'Standard size semi detached',
 '2 storeys terraces with t rear extension',
 'Semi type house in multiples',
 'Tall flats 6-15 storeys',
 'Large detached',
 'Very tall point block flats',
 'Very large detached',
 'Planned balanced mixed estates',
 'Linked and step linked premises',
 'Domestic outbuilding',
 'all_unknown_typology',
 '2 storeys terraces with t rear extension_pct',
 '3-4 storey and smaller flats_pct',
 'Domestic outbuilding_pct',
 'Large detached_pct',
 'Large semi detached_pct',
 'Linked and step linked premises_pct',
 'Medium height flats 5-6 storeys_pct',
 'Planned balanced mixed estates_pct',
 'Semi type house in multiples_pct',
 'Small low terraces_pct',
 'Standard size detached_pct',
 'Standard size semi detached_pct',
 'Tall flats 6-15 storeys_pct',
 'Tall terraces 3-4 storeys_pct',
 'Very large detached_pct',
 'Very tall point block flats_pct',
 'all_unknown_typology_pct',
 ]
 
energy = [ 'num_meters_gas',
 'total_gas',
 'avg_gas',
 'median_gas',
 'num_meters_elec',
 'total_elec',
 'avg_elec',
 'median_elec',
  'gas_EUI_GIA',
 'elec_EUI_GIA',
   ] 

codes = [ 'postcode', 
         'region', 
         'oa21cd',
 'lsoa21cd',
 'msoa21cd',
 'ladcd',
 'lsoa21nm',
 'msoa21nm',
 'ladnm',
 'ladnmw',
 'outcode',
 'latitude', 'longitude'
 ]

dens = [ 'postcode_area',
 'postcode_density',
 ]

cli = [ 'HDD',
 'CDD',
 'HDD_summer',
 'CDD_summer',
 'HDD_winter',
 'CDD_winter',]

bs = [ 'percent_residential',
    'count_all_types_total_buildings', 
      'residential_total_buildings', 
  'all_buildings_GEA',
      'residential_premise_area_total',
        'residential_GEA_total',
        'residential_GIA_total',
        'residential_basement_counts',
        'residential_basement_GEA_total',
        'count_residential_listed_buildings',
        'count_residential_uprns',
        'count_residential_premise_area_null',
        'count_outbuildings',
        'outbuilding_premise_area_total',
        'outbuilding_GEA_total',
        'confidence_floor_area',
        'count_unclassified_domestic',
        'percentage_clean_res_buildings',
        
        'perc_diff_uprns_to_gas_meters',
        'percentage_unknown_res_buildings',
     
 

]

all_cols_list = codes + energy + bs + age + dens +typ +rur+  demogs    + cli 